#!/bin/bash

# Update cagebreak-bin package from github

set -e

TMPDIR="$(mktemp -d)"
ORIG_DIR="${PWD}"
TAR_NAME="cagebreak-bin"

cleanup () {
	rm -rf "${TMPDIR}"
}

for sig in EXIT HUP INT QUIT TERM
do
	# shellcheck disable=2064
	trap "cleanup $sig" $sig
done

git clone https://github.com/project-repo/cagebreak "${TMPDIR}"
cd "${TMPDIR}"
meson build -Dxwayland=true --buildtype=release
ninja -C build
mkdir "${TAR_NAME}"
cp build/cagebreak build/cagebreak.1 build/cagebreak-config.5 LICENSE "${TAR_NAME}/"
tar czvf "${TAR_NAME}.tar.gz" "${TAR_NAME}"
cp "${TAR_NAME}.tar.gz" "${ORIG_DIR}/cagebreak-bin"
cd "${ORIG_DIR}"
